#数据库配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://124.221.198.93:3306/BLOG?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


  #  配置基础路径
  mvc:
    servlet:
      path: /rbm
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


#mybatis配置
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: com.blog.rbm.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8095

#七牛云配置
qiniu:
  domain: http://r9yvz6sq4.hb-bkt.clouddn.com # 访问域名(默认使用七牛云测试域名)
  accessKey: BiRrkH7ymjg6J4YalYu2cLCdadkGFeuimF1bI4ZK # 公钥
  secretKey: 6Ihdk8jwpJ5Nawgfs-eSda6tNTtdaJUkZW3evzVQ # 私钥
  bucketName: rtb  #存储空间名称
